{{- if .Values.admin.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vortex.fullname" . }}-admin
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
    {{- include "vortex.admin.labels" . | nindent 4 }}
spec:
  {{- if not .Values.admin.autoscaling.enabled }}
  replicas: {{ .Values.admin.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vortex.selectorLabels" . | nindent 6 }}
      {{- include "vortex.admin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vortex.labels" . | nindent 8 }}
        {{- include "vortex.admin.labels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vortex.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-admin
          securityContext:
            {{- toYaml .Values.admin.securityContext | nindent 12 }}
          image: "{{ .Values.admin.image.repository }}:{{ .Values.admin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.admin.service.port }}
              protocol: TCP
          {{- if .Values.admin.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.admin.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.admin.livenessProbe }}
          readinessProbe:
            {{- toYaml .Values.admin.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.admin.resources | nindent 12 }}
          {{- with .Values.admin.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}        
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mariadburl
                  key: url
          {{- if .Values.admin.env }}
            {{- range $key, $value := .Values.admin.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
      {{- with .Values.admin.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
