{{- if .Values.traefik }}
  {{- range .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval | default "1m" }}
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ .targetName }}
    template:
      metadata:
        labels:
          reload: "enabled"
  dataFrom:
  - extract:
      key: {{ .key }}
  {{- end }}
{{- end }}
