apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8sapp.fullname" . }}
  labels:
    {{- include "k8sapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      port: {{ .port }}
    {{- end }}
  selector:
    {{- include "k8sapp.selectorLabels" . | nindent 4 }}
