{{- if .Values.traefik }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "k8sapp.fullname" . }}
  labels:
    {{- include "k8sapp.labels" . | nindent 4 }}
spec:
  entryPoints:
  {{- range .Values.traefik.entryPoints }}
  - {{ . }}
  {{- end }}
  routes:
  {{- range .Values.traefik.routes }}
    {{- $service := .service }}
    {{- $port := .port }}
    {{- range .matches }}
  - match: {{ .match }}
    kind: Rule
    services:
    - name: {{ $service }}
      kind: Service
      port: {{ $port }}
    {{- end }}
  {{- end }}
{{- end }}