{{- if .Values.engine.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vortex.fullname" . }}-engine-headless
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
    {{- include "vortex.engine.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "vortex.selectorLabels" . | nindent 4 }}
    {{- include "vortex.engine.selectorLabels" . | nindent 4 }}
  ports:
  {{- range .Values.engine.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .protocol }}
      protocol: {{ .protocol }}
      {{- end }}
  {{- end }}
{{- end }}
