{{- if .Values.engine.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "vortex.fullname" . }}-engine-hpa
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vortex.fullname" . }}-engine
  minReplicas: {{ .Values.engine.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.engine.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.engine.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.engine.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.engine.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.engine.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
