{{- $mysqlSecret := lookup "v1" "Secret" .Release.Namespace "mysql" }}
{{- $rootPassword := "" }}
{{- if $mysqlSecret }}
  {{- $rootPassword = index $mysqlSecret.data "rootPassword" }}
{{- else }}
  {{- $rootPassword = randAlphaNum 16 | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
type: Opaque
data:
  rootPassword: {{ $rootPassword | quote }}
  mariadb-root-password: {{ $rootPassword | quote }}
  mariadb-replication-password: {{ $rootPassword | quote }}
  mariadb-password: {{ $rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ $rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  password: {{ $rootPassword | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadburl
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  url: {{ printf "mysql://root:%s@vortex-mariadb:3306/vortex" ($rootPassword | b64dec) | b64enc }}
