{{- if .Values.opensearch.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.opensearch.secretName | default "opensearch-secret" }}
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  OPENSEARCH_ADMIN_USER: {{ .Values.opensearch.adminUser | b64enc | quote }}
  OPENSEARCH_ADMIN_PASSWORD: {{ if (lookup "v1" "Secret" .Release.Namespace (.Values.opensearch.secretName | default "opensearch-secret")) }}
    {{- (lookup "v1" "Secret" .Release.Namespace (.Values.opensearch.secretName | default "opensearch-secret")).data.OPENSEARCH_ADMIN_PASSWORD }}
  {{- else }}
    {{- randAlphaNum 24 | b64enc | quote }}
  {{- end }}
{{- end }}