{{- if .Values.gatewayWebSocket.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vortex.fullname" . }}-gateway-websocket
  labels:
    {{- include "vortex.labels" . | nindent 4 }}
    {{- include "vortex.gatewayWebSocket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.gatewayWebSocket.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "vortex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/app: gateway-websocket
{{- end }}
