apiVersion: v2
name: vortex
description: A Helm chart to deploy Vortex Stack in Kubernetes
type: application
version: 0.1.1
appVersion: "1.16.0"
dependencies:
  - name: mariadb
    version: 20.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    version: 20.13.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: 22.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled