apiVersion: v2
name: vortex
description: A Helm chart to deploy Vortex Stack in Kubernetes
type: application
version: 0.1.1
appVersion: "1.16.0"
dependencies:
  - name: mariadb
    version: 20.5.3
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
  - name: redis
    version: 21.1.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: 8.5.1
    repository: https://helm.elastic.co
    condition: elasticsearch.enabled
  - name: opensearch
    version: 3.0.0
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.enabled
  - name: rabbitmq
    version: 16.0.2
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: traefik
    version: 35.2.0
    repository: https://traefik.github.io/charts
    condition: traefik.enabled