{{- if and .Values.laststeps .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "50"
spec:
  provider:
    vault:
      server: "http://vortex-vault.{{ .Release.Namespace }}.svc.cluster.local:8200"
      path: "kv"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "es-token"
          key: "token"
          namespace: {{ .Release.Namespace }}
{{- end }}