name: Deploy Helm to gh-pages

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy Helm chart
        run: |
          helm dependency update helm/k8sapp
          helm package helm/k8sapp --destination .
          helm repo index . --url https://juanviola.github.io/charts/stable

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          target-folder: stable
          clean: true
          commit-message: "Update helm-deploy from main"
          filter: '*.tgz,index.yaml' # only copy the index file and the chart tarball
          token: ${{ secrets.GH_PAGES_TOKEN }}