name: Deploy Helm to gh-pages

on:
  push:
    branches:
      - main
    paths:
      - 'helm/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persistent-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Deploy Helm chart
        run: |
          mkdir -p helm_output  # save Helm output directory
          helm dependency update helm/k8sapp
          helm package helm/k8sapp --destination helm_output
          helm repo index helm_output --url https://juanviola.github.io/charts/stable

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: helm_output
          target-folder: stable
          clean: true
          commit-message: "Update helm-deploy from main"
          token: ${{ secrets.GH_PAGES_TOKEN }}
